joint_state_controller:
 type: joint_state_controller/JointStateController
 publish_rate: 50

astra_joint_velocity_controller:
 type: effort_controllers/JointVelocityController
 joint: astra_joint
 pid: {p: 2.0, i: 0.0, d: 0.0}
